fix run arguments

diff --git a/bin/gitlab-vagrant-driver b/bin/gitlab-vagrant-driver
--- a/bin/gitlab-vagrant-driver
+++ b/bin/gitlab-vagrant-driver
@@ -110,19 +110,19 @@ run() {
 		exit "$SYSTEM_FAILURE_EXIT_CODE"
 	}
 	script_name=$(basename "$script")
-	description="$1" && shift || true
-	test -n "$description" || {
-		echo "missing required argument description" >&2
+	stage="$1" && shift || true
+	test -n "$stage" || {
+		echo "missing required argument stage" >&2
 		exit "$SYSTEM_FAILURE_EXIT_CODE"
 	}
-	test -n "$description" && echo "$description"
+	echo "$stage"
 	vagrant upload "$script" "$temp/$script_name" >/dev/null 2>&1 || {
-		echo "failed to upload script $description" >&2
+		echo "failed to upload script $stage" >&2
 		exit "$SYSTEM_FAILURE_EXIT_CODE"
 	}
 	vagrant "$communicator" --command "$temp/$script_name" || {
 		echo $? >"$BUILD_EXIT_CODE_FILE"
-		echo "failed to execute script $description" >&2
+		echo "failed to execute script $stage" >&2
 		exit "$BUILD_FAILURE_EXIT_CODE"
 	}
 }
